{
    "access_token": "00D09000002X1WX!AQEAQExZr4JnB2HopV3SfmKmRE7_xTsUW1J7xcybu39lQ6OYZKapWi_Gh9xbd4OzSTQKnqFNihxIfyP8P94zocnh3KxJ333",
    "instance_url": "https://epam2-dev-ed.my.salesforce.com",
    "id": "https://login.salesforce.com/id/00D09000002X1WXEA0/00509000000KDP7AAO",
    "token_type": "Bearer",
    "issued_at": "1603286399910",
    "signature": "5aZbe4jzSBa50PdDwFEeOkLP+2SR3WHxeM3YaGuQzHw="
}